name: music_player
description: Music player

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
   sdk: flutter
  sqflite:
#    A Flutter plugin for finding commonly used locations on the filesystem.
#  Supports iOS, Android, Linux and MacOS. Not all methods are supported on all platforms.
  path_provider: ^1.6.27
#  A Flutter plugin for launching a URL in the mobile platform. Supports iOS, Android, web, Windows, macOS, and Linux.
  url_launcher: ^5.7.10
#  Media notification for flutter, on android
  media_notification: ^0.0.5
  font_awesome: ^5.10.1
#  A Search App Bar like the one in Gmail and Google Photos.
  floating_search_bar: ^0.3.0
#  A flutter package which contains a collection of some cool and awesome text animations.
  animated_text_kit: ^3.1.0
#  Similar to a ListView, but lets you programmatically jump to any item, by index.
  indexed_list_view: ^1.1.5
#  Clip your widgets with custom shapes provided.
  clippy_flutter: ^1.1.1
#  A Flutter plugin to share content from your Flutter app via the platform's share dialog.
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
#  For logging
  fimber: ^0.4.4
  cupertino_icons: ^1.0.1
  dynamic_theme: ^1.0.1
#  A set of utilities that allow you to easily pass a data Model from a parent Widget down to its descendants.
  scoped_model: ^1.1.0
  flute_music_player: ^0.0.6
  provider: ^4.3.3
  stacked: ^1.7.7
  stacked_services: ^0.6.4
  auto_route: ^0.6.9
  material_floating_search_bar: ^0.2.6
  get_it:
  injectable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
